version: 2
jobs:
  build:
        branches:
          ignore:
            - master
            - /feature-.*/

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
