version: 2
jobs:
  build:
    executors:
      build-main:
        machine: true
    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
