version: 2
executors:
  build-main:
    machine: true
jobs:
  build:
    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
