version: 2
jobs:
  build:
    machine: 
      image: "circleci/classic:latest"
    steps:
      - checkout

      - run:
          name: Create Code Archive
          command: git archive -o dpm-build.zip

      - run:
          name: Publish Build Artifact
          command: echo Not Implemented
