export font_bold
export font_dim
export font_under
export font_blink
export font_invert
export font_hide
export font_reset
export font_bold_end
export font_dim_end
export font_under_end
export font_blink_end
export font_invert_end
export font_hide_end
