version: 1.0
directories:
  install:
    darwin: "/Library/Application\ Support/minecraft"
    windows: ""
  saves: "/saves"
  dpm: "/datapackmanager/scripts"
worlds:
  Template:
    savename: dpm-template
    from-datapack: false
    datapacks:
      - devtools
      - foo
      - bar
selectedworld: Template
